#!/usr/bin/env python3
"""Build Unified-Debugging metadata for KhronosGroup/SPIRV-Tools.

SPIRV-Tools uses CMake/CTest and GoogleTest, so the stable generic machinery
from the fmt metadata builder is reused for test discovery, gcov parsing, and
C++ ground-truth extraction.  This module owns the parts that differ:

* revision-pinned dependencies via ``utils/git-sync-deps``;
* targeted Ninja builds for the optimizer test executable;
* regression/target/all test scopes;
* SPIRV production-source coverage filtering; and
* a CTest-based ``run_one_test.sh`` that does not assume a binary location.
"""

from __future__ import annotations

import argparse
import fcntl
import hashlib
import importlib.util
import json
import os
import re
import shlex
import shutil
import sys
import textwrap
import time
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence, Set, Tuple


PROJECT_DIR = Path(__file__).resolve().parent
DEFECTSC_TPL_DIR = PROJECT_DIR.parent.parent
DEFECTS4C_ROOT = DEFECTSC_TPL_DIR.parent
PROJECT_NAME = PROJECT_DIR.name
BUGS_JSON = PROJECT_DIR / "bugs_list_new.json"
REMOTE_URL = "https://github.com/KhronosGroup/SPIRV-Tools.git"
DATA_FOLDER = "spirv-tools"
BUILD_DIR_NAME = "build_meta_spirv"
GCOV_SIGNAL_HEADER = "__build_meta_spirv_gcov_signal_dump.h"
METADATA_PIPELINE_VERSION = 2

# Old pinned GoogleTest revisions enable their own trailing ``-Werror``.  The
# warning-specific override remains effective even when that generic flag is
# appended later by the dependency's CMake files (notably on GCC 11).
BASE_CFLAGS = "-g -O0 -Wno-error -Wno-error=maybe-uninitialized -fsigned-char"
COV_CFLAGS = f"{BASE_CFLAGS} -fprofile-arcs -ftest-coverage"
COV_LDFLAGS = "-fprofile-arcs -ftest-coverage -lgcov"

RUN_ONE_TEST_SH = textwrap.dedent(r"""
    #!/usr/bin/env bash
    # Auto-generated by build_meta_spirv.py
    set -uo pipefail
    HERE=$(cd "$(dirname "$0")" && pwd)
    TEST_ID="${1:?Usage: $0 <test_id>}"
    BUILD_DIR="$HERE/__BUILD_DIR_NAME__"
    TEST_TIMEOUT="${BUILD_META_TEST_TIMEOUT:-180}"
    CTEST_NAME="${TEST_ID%%::*}"
    if [[ "$TEST_ID" == *"::"* ]]; then
      CASE_NAME="${TEST_ID#*::}"
      OUTPUT=$(GTEST_FILTER="$CASE_NAME" GTEST_COLOR=no \
        ctest --test-dir "$BUILD_DIR" -R "^${CTEST_NAME}$" -V \
          --timeout "$TEST_TIMEOUT" 2>&1)
    else
      OUTPUT=$(ctest --test-dir "$BUILD_DIR" -R "^${CTEST_NAME}$" -V \
        --timeout "$TEST_TIMEOUT" 2>&1)
    fi
    STATUS=$?
    echo "$OUTPUT"
    if [[ $STATUS -ne 0 ]] || echo "$OUTPUT" | grep -Eq '\*\*\*Failed|\[  FAILED  \]|Running 0 tests|No tests were found'; then
      exit 1
    fi
    exit 0
""").lstrip()


def _load_fmt_builder():
    path = PROJECT_DIR.parent / "fmtlib___fmt" / "build_meta_fmt.py"
    spec = importlib.util.spec_from_file_location("_spirv_fmt_metadata_base", path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Unable to load shared metadata builder: {path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


base = _load_fmt_builder()
BugEntry = base.BugEntry
CTestEntry = base.CTestEntry
TestResult = base.TestResult
TestSpec = base.TestSpec

# The reused helpers resolve these values dynamically from their module.
base.PROJECT_DIR = PROJECT_DIR
base.PROJECT_NAME = PROJECT_NAME
base.BUGS_JSON = BUGS_JSON
base.REMOTE_URL = REMOTE_URL
base.BUILD_DIR_NAME = BUILD_DIR_NAME
base.RUN_ONE_TEST_SH = RUN_ONE_TEST_SH
base.GCOV_SIGNAL_HEADER = GCOV_SIGNAL_HEADER


def log(message: str) -> None:
    print(f"[{time.strftime('%H:%M:%S')}] {message}", flush=True)


def _safe_exists(path: Path) -> bool:
    try:
        return path.exists()
    except OSError:
        return False


def default_out_root() -> Path:
    host = DEFECTS4C_ROOT / "out_tmp_dirs" / PROJECT_NAME
    container = Path("/out") / PROJECT_NAME
    return container if _safe_exists(Path("/out")) else host


def default_metadata_dir() -> Path:
    host = DEFECTS4C_ROOT / "out_tmp_dirs/unified_debugging" / DATA_FOLDER / "metadata"
    return Path("/out/unified_debugging") / DATA_FOLDER / "metadata" if _safe_exists(Path("/out")) else host


def default_raw_dir() -> Path:
    host = DEFECTS4C_ROOT / "out_tmp_dirs/unified_debugging" / DATA_FOLDER / "raw"
    return Path("/out/unified_debugging") / DATA_FOLDER / "raw" if _safe_exists(Path("/out")) else host


def acquire_lock(out_root: Path):
    key = hashlib.md5(str(out_root.resolve()).encode("utf-8")).hexdigest()
    path = Path("/tmp") / f".build_meta_spirv.{key}.lock"
    fp = path.open("a+", encoding="utf-8")
    try:
        fcntl.flock(fp.fileno(), fcntl.LOCK_EX | fcntl.LOCK_NB)
    except BlockingIOError:
        fp.close()
        raise RuntimeError(f"Another SPIRV metadata process is using {out_root}")
    fp.seek(0)
    fp.truncate(0)
    fp.write(f"pid={os.getpid()} started={time.strftime('%Y-%m-%d %H:%M:%S')}\n")
    fp.flush()
    return fp


def git_checkout(repo: Path, sha: str, label: str) -> None:
    """Reset sources while preserving dependencies and the incremental build."""
    log(f"  [git] checkout {label}={sha[:10]}")
    base.run(["git", "reset", "--hard"], cwd=repo, check=True)
    base.run(
        ["git", "clean", "-ffdx", "-e", "external/", "-e", f"{BUILD_DIR_NAME}/"],
        cwd=repo,
        check=True,
    )
    rc, _, _ = base.run(["git", "cat-file", "-e", f"{sha}^{{commit}}"], cwd=repo)
    if rc != 0:
        base.run(["git", "fetch", "--all", "--tags"], cwd=repo, check=True, timeout=1200)
    base.run(["git", "checkout", "--force", sha], cwd=repo, check=True)


base._git_checkout = git_checkout


def ensure_dependencies(repo: Path) -> bool:
    """Fetch the dependency revisions declared by the checked-out DEPS file."""
    marker = repo / "external/.build_meta_spirv_deps_ready"
    rc, head, _ = base.run(["git", "rev-parse", "HEAD"], cwd=repo)
    revision = head.strip() if rc == 0 else "unknown"
    required = [
        repo / "external/spirv-headers",
        repo / "external/googletest",
        repo / "external/effcee",
    ]
    if marker.is_file() and marker.read_text(errors="ignore").strip() == revision and all(p.is_dir() for p in required):
        return True

    sync_script = repo / "utils/git-sync-deps"
    if not sync_script.is_file():
        log("  [deps] missing utils/git-sync-deps; refusing unpinned dependency clones")
        return False
    log("  [deps] syncing revision-pinned dependencies")
    rc, out, err = base.run([sys.executable, str(sync_script)], cwd=repo, timeout=1800)
    if rc != 0:
        log(f"  [deps] sync FAILED rc={rc}\n{(out + err)[-3000:]}")
        return False
    if not all(p.is_dir() for p in required):
        missing = ", ".join(str(p.relative_to(repo)) for p in required if not p.is_dir())
        log(f"  [deps] sync completed but required directories are missing: {missing}")
        return False
    marker.parent.mkdir(parents=True, exist_ok=True)
    marker.write_text(revision + "\n", encoding="utf-8")
    return True


def target_names(bug: BugEntry) -> List[str]:
    names = [str(item).strip() for item in bug.test_flags if str(item).strip()]
    return list(dict.fromkeys(names or ["spirv-tools-test_opt"]))


def ninja_target_names(ctest_targets: Sequence[str]) -> List[str]:
    """Map SPIRV's public CTest names to their underlying CMake targets."""
    targets = []
    for name in ctest_targets:
        target = name[len("spirv-tools-"):] if name.startswith("spirv-tools-") else name
        if target and target not in targets:
            targets.append(target)
    return targets


def compile_project(
    repo: Path,
    *,
    jobs: int,
    coverage: bool,
    targets: Sequence[str],
    build_all: bool,
    timeout: int = 2400,
) -> bool:
    if not ensure_dependencies(repo):
        return False

    build_dir = repo / BUILD_DIR_NAME
    build_dir.mkdir(parents=True, exist_ok=True)

    flags = COV_CFLAGS if coverage else BASE_CFLAGS
    if coverage:
        signal_header = base.write_gcov_signal_header(repo)
        flags += f" -include {shlex.quote(str(signal_header))}"
    ldflags = COV_LDFLAGS if coverage else ""
    cmake_args = [
        "cmake", "-G", "Ninja", "-S", str(repo), "-B", str(build_dir),
        "-DCMAKE_BUILD_TYPE=Debug",
        "-DCMAKE_EXPORT_COMPILE_COMMANDS=ON",
        "-DSPIRV_WERROR=OFF",
        "-DSPIRV_SKIP_TESTS=OFF",
        "-DEFFCEE_BUILD_TESTING=OFF",
        "-DCMAKE_C_FLAGS=" + flags,
        "-DCMAKE_CXX_FLAGS=" + flags,
        "-DCMAKE_EXE_LINKER_FLAGS=" + ldflags,
        "-DCMAKE_SHARED_LINKER_FLAGS=" + ldflags,
    ]
    if shutil.which("ccache"):
        cmake_args.extend([
            "-DCMAKE_C_COMPILER_LAUNCHER=ccache",
            "-DCMAKE_CXX_COMPILER_LAUNCHER=ccache",
        ])
    phase = "GCOV" if coverage else "plain"
    log(f"  [build-{phase}] cmake configure")
    rc, out, err = base.run(cmake_args, cwd=repo, timeout=600)
    if rc != 0:
        log(f"  [build-{phase}] configure FAILED rc={rc}\n{(out + err)[-3000:]}")
        return False

    build_targets = ninja_target_names(targets)
    command = ["ninja", "-C", str(build_dir), f"-j{max(1, jobs)}"]
    if not build_all:
        command.extend(build_targets)
    log(f"  [build-{phase}] {' '.join(build_targets) if not build_all else 'default target'}")
    rc, out, err = base.run(command, cwd=repo, timeout=timeout)
    if rc != 0:
        log(f"  [build-{phase}] ninja FAILED rc={rc}\n{(out + err)[-3000:]}")
        return False
    if coverage and not list(build_dir.rglob("*.gcno")):
        log("  [build-GCOV] WARNING: no *.gcno files found")
    return True


GTEST_MACROS = ("TEST", "TEST_F", "TEST_P", "TYPED_TEST", "TYPED_TEST_P")
_GTEST_MACRO_RE = re.compile(r"\b(" + "|".join(GTEST_MACROS) + r")\s*\(")


def _matching(text: str, start: int, opening: str, closing: str) -> int:
    depth = 0
    quote = ""
    escaped = False
    for index in range(start, len(text)):
        char = text[index]
        if quote:
            if escaped:
                escaped = False
            elif char == "\\":
                escaped = True
            elif char == quote:
                quote = ""
            continue
        if char in ('"', "'"):
            quote = char
        elif char == opening:
            depth += 1
        elif char == closing:
            depth -= 1
            if depth == 0:
                return index
    return -1


def _split_args(text: str) -> List[str]:
    args: List[str] = []
    start = 0
    depths = {"(": 0, "[": 0, "{": 0, "<": 0}
    pairs = {")": "(", "]": "[", "}": "{", ">": "<"}
    for index, char in enumerate(text):
        if char in depths:
            depths[char] += 1
        elif char in pairs and depths[pairs[char]]:
            depths[pairs[char]] -= 1
        elif char == "," and not any(depths.values()):
            args.append(text[start:index].strip())
            start = index + 1
    args.append(text[start:].strip())
    return args


def gtest_blocks(source: str) -> List[dict]:
    blocks: List[dict] = []
    for match in _GTEST_MACRO_RE.finditer(source):
        open_paren = source.find("(", match.start())
        close_paren = _matching(source, open_paren, "(", ")")
        if close_paren < 0:
            continue
        args = _split_args(source[open_paren + 1:close_paren])
        if len(args) < 2:
            continue
        open_brace = source.find("{", close_paren)
        close_brace = _matching(source, open_brace, "{", "}") if open_brace >= 0 else close_paren
        end = close_brace + 1 if close_brace >= 0 else close_paren + 1
        blocks.append({
            "name": f"{args[0].strip()}.{args[1].strip()}",
            "macro": match.group(1),
            "suite": args[0].strip(),
            "line_start": source.count("\n", 0, match.start()) + 1,
            "line_end": source.count("\n", 0, end) + 1,
        })
    return blocks


def _changed_new_lines(diff: str) -> Dict[str, Set[int]]:
    changed: Dict[str, Set[int]] = {}
    current = ""
    line_no = 0
    for line in diff.splitlines():
        if line.startswith("+++ b/"):
            current = line[6:].strip()
            changed.setdefault(current, set())
            continue
        hunk = re.match(r"@@\s+-\d+(?:,\d+)?\s+\+(?P<start>\d+)(?:,\d+)?\s+@@", line)
        if hunk:
            line_no = int(hunk.group("start"))
            continue
        if not current or not line_no:
            continue
        if line.startswith("+") and not line.startswith("+++"):
            changed[current].add(line_no)
            line_no += 1
        elif line.startswith("-") and not line.startswith("---"):
            # A deletion has no new-side line of its own.  Mark its insertion
            # point so deletion-only changes still select the enclosing test.
            changed[current].add(line_no)
            continue
        else:
            line_no += 1
    return changed


_GTEST_INSTANTIATE_RE = re.compile(r"\bINSTANTIATE_TEST_(?:SUITE|CASE)_P\s*\(")


def gtest_instantiation_blocks(source: str) -> List[dict]:
    """Return parameterized-suite instantiation ranges and base suite names."""
    blocks: List[dict] = []
    for match in _GTEST_INSTANTIATE_RE.finditer(source):
        open_paren = source.find("(", match.start())
        close_paren = _matching(source, open_paren, "(", ")")
        if close_paren < 0:
            continue
        args = _split_args(source[open_paren + 1:close_paren])
        if len(args) < 2:
            continue
        blocks.append({
            "suite": args[1].strip(),
            "line_start": source.count("\n", 0, match.start()) + 1,
            "line_end": source.count("\n", 0, close_paren + 1) + 1,
        })
    return blocks


def regression_case_names(repo: Path, bug: BugEntry) -> Set[str]:
    if not bug.test_files or not bug.sha_before or not bug.sha_after:
        return set()
    rc, diff, _ = base.run(
        ["git", "diff", "--unified=0", bug.sha_before, bug.sha_after, "--", *bug.test_files],
        cwd=repo,
    )
    changed = _changed_new_lines(diff) if rc == 0 else {}
    names: Set[str] = set()
    for test_file in bug.test_files:
        rc_show, source, _ = base.run(["git", "show", f"{bug.sha_after}:{test_file}"], cwd=repo)
        if rc_show != 0:
            continue
        file_changes = changed.get(test_file, set())
        test_blocks = gtest_blocks(source)
        for block in test_blocks:
            if any(block["line_start"] <= line <= block["line_end"] for line in file_changes):
                names.add(block["name"])
        parameterized_by_suite: Dict[str, Set[str]] = {}
        for block in test_blocks:
            if block.get("macro") == "TEST_P":
                parameterized_by_suite.setdefault(block["suite"], set()).add(block["name"])
        for block in gtest_instantiation_blocks(source):
            if any(block["line_start"] <= line <= block["line_end"] for line in file_changes):
                names.update(parameterized_by_suite.get(block["suite"], set()))
    return names


def _case_matches(candidate: str, wanted: str) -> bool:
    if candidate == wanted:
        return True
    # Parameterized GoogleTest names may add a prefix and/or numeric suffix.
    return candidate.endswith("/" + wanted) or candidate.startswith(wanted + "/") or f"/{wanted}/" in candidate


def _case_suite(case_name: str) -> str:
    suite = str(case_name or "").split(".", 1)[0]
    parts = [part for part in suite.split("/") if part]
    while parts and parts[-1].isdigit():
        parts.pop()
    return parts[-1] if parts else suite


def order_specs_with_regressions_first(
    specs: Sequence[TestSpec], regression_names: Set[str]
) -> Tuple[List[TestSpec], List[TestSpec]]:
    """Order exact regressions, their suites, then all remaining cases."""
    regressions = [
        spec for spec in specs
        if spec.gtest_filter and any(
            _case_matches(spec.gtest_filter, wanted) for wanted in regression_names
        )
    ]
    regression_ids = {spec.test_id for spec in regressions}
    regression_suites = {_case_suite(name) for name in regression_names}
    same_suite = [
        spec for spec in specs
        if spec.test_id not in regression_ids
        and spec.gtest_filter
        and _case_suite(spec.gtest_filter) in regression_suites
    ]
    prioritized_ids = regression_ids | {spec.test_id for spec in same_suite}
    remaining = [spec for spec in specs if spec.test_id not in prioritized_ids]
    return regressions + same_suite + remaining, regressions


def select_specs(
    repo: Path,
    bug: BugEntry,
    all_ctest_names: Sequence[str],
    *,
    scope: str,
    max_tests: int,
) -> Tuple[List[TestSpec], dict]:
    target_ctest_names: List[str] = []
    for requested in target_names(bug):
        pattern = re.compile("^" + re.escape(requested).replace(r"\*", ".*") + "$")
        for ctest_name in all_ctest_names:
            if pattern.match(ctest_name) and ctest_name not in target_ctest_names:
                target_ctest_names.append(ctest_name)
    ctest_names = list(all_ctest_names) if scope == "all" else target_ctest_names
    specs = base.discover_test_specs(repo / BUILD_DIR_NAME, ctest_names)
    changed_cases = regression_case_names(repo, bug)
    ordered, regression_specs = order_specs_with_regressions_first(specs, changed_cases)
    detail = {
        "requested_scope": scope,
        "effective_scope": scope,
        "regression_cases": sorted(changed_cases),
        "matched_regression_tests": len(regression_specs),
        "candidate_tests": len(specs),
        "max_tests": max_tests,
        "selection_policy": "regression_cases_first_then_same_suite_then_fill_to_max_tests",
    }
    if scope == "regression":
        if regression_specs:
            ordered = regression_specs
        else:
            detail["effective_scope"] = "target"
            detail["scope_fallback"] = "no_changed_gtest_case_matched"
    selected = ordered[:max_tests] if max_tests > 0 else ordered
    detail["selection_truncated"] = len(selected) < len(ordered)
    regression_ids = {item.test_id for item in regression_specs}
    detail["selected_regression_tests"] = sum(
        spec.test_id in regression_ids for spec in selected
    )
    return selected, detail


def _is_production_source(rel_path: str) -> bool:
    rel = rel_path.replace("\\", "/").lstrip("./")
    if not rel.endswith((".h", ".hpp", ".hh", ".c", ".cc", ".cpp", ".cxx")):
        return False
    return rel.startswith("source/") or rel.startswith("include/spirv-tools/")


def filter_production_coverage(cov_map: Dict[str, List[str]]) -> Dict[str, List[str]]:
    return {rel: funcs for rel, funcs in cov_map.items() if _is_production_source(rel)}


def _normalize_cpp_function(name: str) -> str:
    value = re.sub(r"\s+", " ", str(name or "")).strip()
    value = base._strip_cpp_parameter_list(value)
    value = re.sub(r"^(?:virtual|static|constexpr|const|inline|typename)\s+", "", value)
    value = base._drop_cpp_return_type(value)
    value = base._strip_cpp_template_args(value)
    return value.strip()


base._is_production_source = _is_production_source
base.filter_production_coverage = filter_production_coverage
base._normalize_cpp_function = _normalize_cpp_function


def _compile_cmd(repo: Path, jobs: int, targets: Sequence[str]) -> str:
    target_text = " ".join(shlex.quote(item) for item in ninja_target_names(targets))
    launcher = (
        "-DCMAKE_C_COMPILER_LAUNCHER=ccache "
        "-DCMAKE_CXX_COMPILER_LAUNCHER=ccache "
        if shutil.which("ccache") else ""
    )
    return (
        f"cd {shlex.quote(str(repo))} && cmake -G Ninja -S . -B {BUILD_DIR_NAME} "
        f"-DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON "
        f"-DSPIRV_WERROR=OFF -DSPIRV_SKIP_TESTS=OFF -DEFFCEE_BUILD_TESTING=OFF "
        f"{launcher}"
        f"-DCMAKE_CXX_FLAGS='{COV_CFLAGS}' && "
        f"ninja -C {BUILD_DIR_NAME} -j{jobs} {target_text}"
    )


def _empty_record(bug: BugEntry, repo: Path, compile_cmd: str, error: str) -> dict:
    source_file = str(repo / bug.src_files[0]) if bug.src_files else ""
    return {
        "bug_id": bug.bug_id,
        "dataset_name": "defects4c",
        "language": "C++",
        "project": PROJECT_NAME,
        "commit_after": bug.sha_after,
        "commit_before": bug.sha_before,
        "source_file": source_file,
        "source_basename": os.path.basename(source_file) if source_file else "",
        "test_files": bug.test_files,
        "compile_cmd": compile_cmd,
        "test_cmd_template": "",
        "type_name": bug.type_name,
        "ground_truth_functions": [],
        "ground_truth": [],
        "tests": [],
        "phase_info": {"errors": [error]},
        "build_error": error,
    }


def _rebind_specs(build_dir: Path, selected: Sequence[TestSpec]) -> List[TestSpec]:
    entries = {entry.name: entry for entry in base.list_ctest_entries(build_dir)}
    rebound: List[TestSpec] = []
    for spec in selected:
        entry = entries.get(spec.ctest_name, CTestEntry(spec.ctest_name))
        rebound.append(TestSpec(
            test_id=spec.test_id,
            ctest_name=spec.ctest_name,
            command=entry.command,
            working_directory=entry.working_directory,
            gtest_filter=spec.gtest_filter,
        ))
    return rebound


def _run_outcomes(build_dir: Path, specs: Sequence[TestSpec], timeout: int, label: str) -> Tuple[List[TestResult], Dict[str, str]]:
    rows: List[TestResult] = []
    outcomes: Dict[str, str] = {}
    for index, spec in enumerate(specs, 1):
        passed, output = base.run_one_test_spec(build_dir, spec, timeout=timeout, asan=False)
        outcome = "PASS" if passed else "FAIL"
        outcomes[spec.test_id] = outcome
        rows.append(TestResult(
            test_id=spec.test_id,
            outcome=outcome,
            fail_reason="" if passed else output[-3000:],
            actual_output="" if passed else output[-3000:],
        ))
        if index % 25 == 0 or index == len(specs):
            failures = sum(1 for value in outcomes.values() if value == "FAIL")
            log(f"  [{label}] {index}/{len(specs)} (fail={failures})")
    return rows, outcomes


def process_bug(
    bug: BugEntry,
    out_root: Path,
    metadata_dir: Path,
    raw_dir: Path,
    *,
    jobs: int,
    test_timeout: int,
    skip_if_exists: bool,
    clone_if_missing: bool,
    skip_coverage: bool,
    dual_run: bool,
    test_scope: str,
    max_tests: int,
) -> Optional[Path]:
    filename = f"{bug.safe_bug_id}_meta.json"
    metadata_path = metadata_dir / filename
    raw_path = raw_dir / filename
    if skip_if_exists and metadata_path.is_file():
        try:
            existing = json.loads(metadata_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            existing = {}
        existing_phase = existing.get("phase_info") if isinstance(existing, dict) else {}
        current = (
            isinstance(existing_phase, dict)
            and existing.get("project") == PROJECT_NAME
            and existing_phase.get("test_granularity") == "gtest_case"
            and int(existing_phase.get("pipeline_version") or 0) == METADATA_PIPELINE_VERSION
            and existing_phase.get("requested_scope") == test_scope
            and int(existing_phase.get("max_tests") or 0) == int(max_tests)
            and bool(existing_phase.get("dual_run")) == bool(dual_run)
            and bool(existing_phase.get("skip_coverage")) == bool(skip_coverage)
            and not existing_phase.get("errors")
            and bool(existing.get("tests"))
        )
        if current:
            log(f"[skip] {bug.bug_id}")
            return metadata_path
        log(f"[rerun] {bug.bug_id} existing metadata does not match requested pipeline options")

    log(f"=== {bug.bug_id} | {bug.type_name or ''} ===")
    try:
        repo = base.ensure_repo(out_root, bug.sha_after, clone_if_missing=clone_if_missing)
    except Exception as exc:
        log(f"  [error] repo: {exc}")
        return None

    targets = target_names(bug)
    compile_cmd = _compile_cmd(repo, jobs, targets)
    source_file = str(repo / bug.src_files[0]) if bug.src_files else ""
    test_cmd_template = f"bash {shlex.quote(str(repo / 'run_one_test.sh'))} {{test_id}}"
    phase_info = {
        "pipeline_version": METADATA_PIPELINE_VERSION,
        "dual_run": dual_run,
        "skip_coverage": skip_coverage,
        "test_granularity": "gtest_case",
        "build_targets": targets,
        "max_tests": max_tests,
        "selection_policy": "regression_cases_first_then_same_suite_then_fill_to_max_tests",
        "errors": [],
    }

    try:
        base.checkout_buggy(repo, bug)
        if not compile_project(
            repo, jobs=jobs, coverage=False, targets=targets,
            build_all=test_scope == "all",
        ):
            record = _empty_record(bug, repo, compile_cmd, "buggy_phase_a_compile_failed")
            base._write_meta(raw_path, record)
            base._write_meta(metadata_path, record)
            return None
        base.write_run_one_test(repo)
        build_dir = repo / BUILD_DIR_NAME
        all_ctest_names = base.list_ctest_tests(build_dir)
        selected, scope_info = select_specs(
            repo,
            bug,
            all_ctest_names,
            scope=test_scope,
            max_tests=max_tests,
        )
    except Exception as exc:
        log(f"  [error] discovery: {exc}")
        record = _empty_record(bug, repo, compile_cmd, f"discovery_failed:{exc}")
        base._write_meta(raw_path, record)
        base._write_meta(metadata_path, record)
        return None

    phase_info.update(scope_info)
    phase_info["all_ctest_tests"] = len(all_ctest_names)
    phase_info["selected_ctest_tests"] = len({spec.ctest_name for spec in selected})
    phase_info["all_tests"] = scope_info.get("candidate_tests")
    phase_info["selected_tests"] = len(selected)
    if not selected:
        phase_info["errors"].append("no_tests_selected")
    log(
        f"  [tests] ctest={len(all_ctest_names)}, selected_cases={len(selected)}, "
        f"scope={phase_info.get('effective_scope')}"
    )

    results, _ = _run_outcomes(build_dir, selected, test_timeout, "phaseA-buggy")
    fixed_map: Dict[str, str] = {}
    if dual_run:
        try:
            base.checkout_fixed(repo, bug)
            if compile_project(
                repo, jobs=jobs, coverage=False, targets=targets,
                build_all=test_scope == "all",
            ):
                _, fixed_map = _run_outcomes(
                    repo / BUILD_DIR_NAME,
                    _rebind_specs(repo / BUILD_DIR_NAME, selected),
                    test_timeout,
                    "phaseA-fixed",
                )
            else:
                phase_info["errors"].append("fixed_phase_a_compile_failed")
        except Exception as exc:
            phase_info["errors"].append(f"fixed_phase_exception:{exc}")

    raw_cov: Dict[str, List[str]] = {}
    meta_cov: Dict[str, List[str]] = {}
    cov_errors: Dict[str, str] = {}
    if not skip_coverage:
        try:
            base.checkout_buggy(repo, bug)
            if compile_project(
                repo, jobs=jobs, coverage=True, targets=targets,
                build_all=test_scope == "all",
            ):
                cov_dir = repo / BUILD_DIR_NAME
                cov_specs = _rebind_specs(cov_dir, selected)
                for index, spec in enumerate(cov_specs, 1):
                    base.clear_gcda(cov_dir)
                    base.run_one_test_spec(cov_dir, spec, timeout=test_timeout, asan=False)
                    coverage, error = base.collect_coverage(repo, cov_dir, verbose=index <= 2)
                    raw_cov[spec.test_id] = base.coverage_to_qualified(coverage)
                    meta_cov[spec.test_id] = base.coverage_to_qualified(filter_production_coverage(coverage))
                    cov_errors[spec.test_id] = error
                    if index % 25 == 0 or index == len(cov_specs):
                        log(f"  [phaseB] {index}/{len(cov_specs)}")
            else:
                phase_info["errors"].append("coverage_compile_failed")
                cov_errors.update({spec.test_id: "coverage_compile_failed" for spec in selected})
        except Exception as exc:
            phase_info["errors"].append(f"coverage_phase_exception:{exc}")
            cov_errors.update({spec.test_id: f"coverage_phase_exception:{exc}" for spec in selected})

    raw_results: List[TestResult] = []
    metadata_results: List[TestResult] = []
    for result in results:
        common = dict(
            test_id=result.test_id,
            outcome=result.outcome,
            outcome_fixed=fixed_map.get(result.test_id, "NOT_RUN"),
            fail_reason=result.fail_reason,
            actual_output=result.actual_output,
            coverage_error=cov_errors.get(result.test_id, ""),
        )
        raw_results.append(TestResult(**common, covered_functions=raw_cov.get(result.test_id, [])))
        metadata_results.append(TestResult(**common, covered_functions=meta_cov.get(result.test_id, [])))

    base.write_run_one_test(repo)
    ground_truth = base.extract_ground_truth(bug, repo)
    common_record = {
        "bug_id": bug.bug_id,
        "dataset_name": "defects4c",
        "language": "C++",
        "project": PROJECT_NAME,
        "commit_after": bug.sha_after,
        "commit_before": bug.sha_before,
        "source_file": source_file,
        "source_basename": os.path.basename(source_file) if source_file else "",
        "test_files": bug.test_files,
        "compile_cmd": compile_cmd,
        "test_cmd_template": test_cmd_template,
        "type_name": bug.type_name,
        "ground_truth_functions": ground_truth,
        "ground_truth": [f"{source_file}::{name}" for name in ground_truth] if source_file else [],
    }
    raw_record = {
        **common_record,
        "phase_info": {**phase_info, "coverage_scope": "full_gcov"},
        "tests": [base._test_to_dict(row) for row in raw_results],
    }
    metadata_record = {
        **common_record,
        "phase_info": {
            **phase_info,
            "coverage_scope": "production_source_only",
            "coverage_filter": "keep source/* and include/spirv-tools/*",
        },
        "tests": [base._test_to_dict(row) for row in metadata_results],
    }
    base._write_meta(raw_path, raw_record)
    base._write_meta(metadata_path, metadata_record)
    log(f"  [ok] wrote {metadata_path}")
    return None if phase_info["errors"] else metadata_path


def copy_bug_catalog(metadata_dir: Path) -> None:
    destination = metadata_dir / BUGS_JSON.name
    if not destination.is_file() or destination.read_bytes() != BUGS_JSON.read_bytes():
        shutil.copy2(BUGS_JSON, destination)


def check_required_tools() -> bool:
    missing = [name for name in ("git", "cmake", "ninja", "ctest", "gcc", "g++", "gcov") if not shutil.which(name)]
    if missing:
        log(f"[error] missing required tools: {', '.join(missing)}")
        return False
    return True


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(description="Build Unified-Debugging metadata for SPIRV-Tools.")
    parser.add_argument("--sha", action="append", default=[])
    parser.add_argument("--limit", type=int, default=0)
    parser.add_argument("--out-root", type=Path, default=default_out_root())
    parser.add_argument("--metadata-dir", type=Path, default=default_metadata_dir())
    parser.add_argument("--raw-dir", type=Path, default=default_raw_dir())
    parser.add_argument("--jobs", type=int, default=2)
    parser.add_argument("--test-timeout", type=int, default=180)
    parser.add_argument("--test-scope", choices=("regression", "target", "all"), default="target")
    parser.add_argument(
        "--max-tests",
        type=int,
        default=200,
        help="Maximum cases after regression-first ordering. Use 0 for unlimited.",
    )
    parser.add_argument("--skip-coverage", action="store_true")
    parser.add_argument("--dual-run", dest="dual_run", action="store_true", default=True)
    parser.add_argument("--single-run", dest="dual_run", action="store_false")
    parser.add_argument("--skip-if-exists", action="store_true")
    parser.add_argument("--clone", action="store_true")
    parser.add_argument("--include-manual-status-2", action="store_true")
    parser.add_argument("--list", action="store_true")
    args = parser.parse_args(argv)

    bugs = base.load_bugs()
    if not args.include_manual_status_2:
        bugs = [bug for bug in bugs if int(bug.raw.get("status_manual") or 0) == 1]
    if args.sha:
        wanted = tuple(item for item in args.sha if item)
        bugs = [bug for bug in bugs if bug.sha_after in wanted or bug.sha_after.startswith(wanted)]
    if args.limit:
        bugs = bugs[:args.limit]
    if args.list:
        for bug in bugs:
            print(f"{bug.sha_after}\t{bug.bug_id}\t{','.join(bug.test_files)}")
        return 0
    if not bugs:
        log("No matching bugs.")
        return 1
    if not check_required_tools():
        return 4

    args.metadata_dir.mkdir(parents=True, exist_ok=True)
    args.raw_dir.mkdir(parents=True, exist_ok=True)
    copy_bug_catalog(args.metadata_dir)
    log(
        f"Will process {len(bugs)} bug(s), scope={args.test_scope}, "
        f"max_tests={max(0, args.max_tests)}, jobs={max(1, args.jobs)}."
    )

    try:
        lock = acquire_lock(args.out_root)
    except RuntimeError as exc:
        log(f"[error] {exc}")
        return 3
    failures = 0
    try:
        for bug in bugs:
            try:
                result = process_bug(
                    bug,
                    args.out_root,
                    args.metadata_dir,
                    args.raw_dir,
                    jobs=max(1, args.jobs),
                    test_timeout=max(1, args.test_timeout),
                    skip_if_exists=args.skip_if_exists,
                    clone_if_missing=args.clone,
                    skip_coverage=args.skip_coverage,
                    dual_run=args.dual_run,
                    test_scope=args.test_scope,
                    max_tests=max(0, args.max_tests),
                )
                if result is None:
                    failures += 1
            except KeyboardInterrupt:
                return 130
            except Exception as exc:
                failures += 1
                log(f"  [exception] {bug.bug_id}: {exc}")
    finally:
        fcntl.flock(lock.fileno(), fcntl.LOCK_UN)
        lock.close()
    log(f"DONE. fail={failures}/{len(bugs)}")
    return 0 if failures == 0 else 2


if __name__ == "__main__":
    raise SystemExit(main())
